/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConversationId = bigint;
export type Id = bigint;
export type ImageAssetUrl = string;
export interface Message {
  'id' : Id,
  'content' : string,
  'read' : boolean,
  'sender' : UserId,
  'conversationId' : ConversationId,
  'timestamp' : bigint,
}
export interface Post {
  'id' : bigint,
  'author' : UserId,
  'timestamp' : bigint,
  'caption' : string,
  'images' : Array<ImageAssetUrl>,
}
export type PostId = bigint;
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'username' : Username,
  'displayName' : string,
  'followers' : Array<UserId>,
  'following' : Array<UserId>,
  'avatar' : [] | [Uint8Array],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSearchResult {
  'principal' : Principal,
  'profile' : UserProfile,
}
export type Username = string;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Handles Internet Identity authentication and session management (requires user role)
   */
  'authenticate' : ActorMethod<[], undefined>,
  /**
   * / Creates a new post with up to 10 images (requires user role)
   */
  'createPost' : ActorMethod<[string, Array<ImageAssetUrl>], PostId>,
  /**
   * / Follows another user (requires user role)
   */
  'followUser' : ActorMethod<[UserId], undefined>,
  /**
   * / Get caller's user profile (required by frontend)
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Retrieves a user's feed with posts from users they follow (requires user role)
   */
  'getFeed' : ActorMethod<[], Array<Post>>,
  /**
   * / Gets all messages for a conversation (requires user role and participation)
   */
  'getMessages' : ActorMethod<[ConversationId], Array<Message>>,
  /**
   * / Get any user's profile (own profile or admin can view any)
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Lists all conversations for the caller (requires user role)
   */
  'listConversations' : ActorMethod<[], Array<ConversationId>>,
  /**
   * / Save caller's user profile (required by frontend)
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Search for users by username (requires user role)
   */
  'searchUsers' : ActorMethod<[string], Array<UserSearchResult>>,
  /**
   * / Sends a message in a conversation (requires user role and participation)
   */
  'sendMessage' : ActorMethod<[ConversationId, string], undefined>,
  /**
   * / User signup and onboarding flow (accessible to guests to create accounts)
   */
  'signUp' : ActorMethod<[Username, string], undefined>,
  /**
   * / Starts a new conversation with another user (requires user role)
   */
  'startConversation' : ActorMethod<[UserId], ConversationId>,
  /**
   * / Unfollows another user (requires user role)
   */
  'unfollowUser' : ActorMethod<[UserId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];