/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ImageAssetUrl = IDL.Text;
export const PostId = IDL.Nat;
export const UserId = IDL.Principal;
export const Username = IDL.Text;
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : Username,
  'displayName' : IDL.Text,
  'followers' : IDL.Vec(UserId),
  'following' : IDL.Vec(UserId),
  'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'author' : UserId,
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'images' : IDL.Vec(ImageAssetUrl),
});
export const ConversationId = IDL.Nat;
export const Id = IDL.Nat;
export const Message = IDL.Record({
  'id' : Id,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'sender' : UserId,
  'conversationId' : ConversationId,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticate' : IDL.Func([], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Vec(ImageAssetUrl)], [PostId], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationId)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'sendMessage' : IDL.Func([ConversationId, IDL.Text], [], []),
  'signUp' : IDL.Func([Username, IDL.Text], [], []),
  'startConversation' : IDL.Func([UserId], [ConversationId], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ImageAssetUrl = IDL.Text;
  const PostId = IDL.Nat;
  const UserId = IDL.Principal;
  const Username = IDL.Text;
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : Username,
    'displayName' : IDL.Text,
    'followers' : IDL.Vec(UserId),
    'following' : IDL.Vec(UserId),
    'avatar' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'author' : UserId,
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'images' : IDL.Vec(ImageAssetUrl),
  });
  const ConversationId = IDL.Nat;
  const Id = IDL.Nat;
  const Message = IDL.Record({
    'id' : Id,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'sender' : UserId,
    'conversationId' : ConversationId,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticate' : IDL.Func([], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Vec(ImageAssetUrl)], [PostId], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeed' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listConversations' : IDL.Func([], [IDL.Vec(ConversationId)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
    'sendMessage' : IDL.Func([ConversationId, IDL.Text], [], []),
    'signUp' : IDL.Func([Username, IDL.Text], [], []),
    'startConversation' : IDL.Func([UserId], [ConversationId], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };